browser=chrome
url=https://magento.softwaretestingboard.com/
username=gk619dx@gmail.com
password=YEZDI@1990
firstname=Gopi
lastname= S
mobileno=7656765678
street=Tambaram
city=Chennai
state=Tamilnadu
zipcode=620019
country=India